#!/bin/sh

# source common functions; exit if missing
if [[ -f ${UKWACOMMONDIR}/common.sh ]]; then source ${UKWACOMMONDIR}/common.sh; else echo "ERROR: ${UKWACOMMONDIR}/common.sh missing"; exit 1; fi
NOPREFIX=1
DEBUG=

SERVICE=redis
USER=$(id --user --name)
GROUP=$(id --group --name)
BASEDIR=/opt
REDISDATADIR=${BASEDIR}/${SERVICE}
REDISCFGDIR=/etc/${SERVICE}
REDISLOGDIR=/var/log/${SERVICE}


# functions ----------
function install_redis {
	log DEBUG "install_redis"
	if ! [[ $(which redis-server 2> /dev/null) ]]; then
		log INFO "Installing redis"
		sudo dnf install -y redis
		sudo usermod -aG redis ${USER}
	else
		log WARNING "redis already installed"
	fi

	# directories, permissions
	[[ -d ${REDISDATADIR} ]] || sudo mkdir -p ${REDISDATADIR}
	[[ -d ${REDISCFGDIR} ]] || sudo mkdir -p ${REDISCFGDIR}
	[[ -d ${REDISLOGDIR} ]] || sudo mkdir -p ${REDISLOGDIR}
	if ! [[ -d /etc/redis/_original/ ]]; then
		log INFO "Removing redis defaults"
		sudo mkdir /etc/redis/_original
		sudo mv /etc/redis/* /etc/redis/_original/ 2> /dev/null
	fi
}

function amend_permissions {
	log DEBUG "amend_permissions"
	sudo chown -R redis:redis ${REDISDATADIR} ${REDISCFGDIR} ${REDISLOGDIR}
}

function configure_selinux {
	log DEBUG "configure_selinux"
	log INFO "Add redis ${REDISDATADIR} policy"
	sudo semanage fcontext -a -t redis_var_lib_t ${REDISDATADIR}'(/.*)?'
	echo

	log DEBUG "restore_redis_selinux"
	sudo restorecon -R ${REDISDATADIR}
	sudo restorecon -R ${REDISCFGDIR}
	sudo restorecon -R ${REDISLOGDIR}
}

# script -------------
ensure_not_root
install_redis
copy_directory fs
amend_permissions
configure_selinux
log_stop
