#!/bin/env bash

# source common or die
if [[ -f ~/bin/common ]]; then source ~/bin/common; else echo "ERROR: ~/bin/common missing"; exit 1; fi


# globals -----
SERVICE=redis
NOPREFIX=1
DEBUG=


# script -----
sudo systemctl daemon-reload

status=$(systemctl is-active ${SERVICE}.service)
if [[ ${status} != 'active' ]]; then
	log INFO "Enabling and starting ${SERVICE}"
	sudo systemctl enable ${SERVICE}
	sudo systemctl start ${SERVICE}
fi

systemctl status ${SERVICE}
log_stop
